-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.ai_suggestions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  suggestion_id text NOT NULL UNIQUE CHECK (length(suggestion_id) > 0),
  vault_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  status USER-DEFINED NOT NULL DEFAULT 'pending'::suggestion_status,
  suggestion_type USER-DEFINED NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  reasoning text,
  confidence_score numeric CHECK (confidence_score >= 0::numeric AND confidence_score <= 1::numeric),
  projected_apy_improvement numeric,
  projected_risk_change numeric,
  expected_return numeric,
  suggestion_data jsonb NOT NULL CHECK (jsonb_typeof(suggestion_data) = 'object'::text),
  sentiment_data jsonb,
  market_data jsonb,
  applied_at timestamp with time zone,
  dismissed_at timestamp with time zone,
  user_feedback text,
  CONSTRAINT ai_suggestions_pkey PRIMARY KEY (id),
  CONSTRAINT ai_suggestions_vault_id_fkey FOREIGN KEY (vault_id) REFERENCES public.vaults(id)
);
CREATE TABLE public.backtest_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  backtest_id text NOT NULL UNIQUE CHECK (length(backtest_id) > 0),
  vault_id uuid,
  vault_config jsonb NOT NULL CHECK (jsonb_typeof(vault_config) = 'object'::text),
  timeframe_start timestamp with time zone NOT NULL,
  timeframe_end timestamp with time zone NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::backtest_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  total_return numeric,
  annualized_return numeric,
  volatility numeric,
  sharpe_ratio numeric,
  max_drawdown numeric,
  win_rate numeric,
  benchmark_return numeric,
  alpha numeric,
  beta numeric,
  results jsonb DEFAULT '{}'::jsonb,
  error_message text,
  CONSTRAINT backtest_results_pkey PRIMARY KEY (id),
  CONSTRAINT backtest_results_vault_id_fkey FOREIGN KEY (vault_id) REFERENCES public.vaults(id)
);
CREATE TABLE public.chat_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  message_id text NOT NULL UNIQUE CHECK (length(message_id) > 0),
  session_id uuid NOT NULL,
  role USER-DEFINED NOT NULL,
  content text NOT NULL CHECK (length(content) > 0),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  tokens_used integer,
  model text,
  response_type text,
  vault_snapshot jsonb,
  market_context text,
  web_search_used boolean DEFAULT false,
  sequence_number integer NOT NULL CHECK (sequence_number >= 0),
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.chat_sessions(id)
);
CREATE TABLE public.chat_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id text NOT NULL UNIQUE CHECK (length(session_id) > 0),
  user_id uuid,
  vault_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  status USER-DEFINED NOT NULL DEFAULT 'active'::chat_session_status,
  network text,
  initial_prompt text,
  total_messages integer NOT NULL DEFAULT 0,
  vault_generated boolean NOT NULL DEFAULT false,
  vault_deployed boolean NOT NULL DEFAULT false,
  CONSTRAINT chat_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT chat_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT chat_sessions_vault_id_fkey FOREIGN KEY (vault_id) REFERENCES public.vaults(id)
);
CREATE TABLE public.marketplace_listings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  listing_id text NOT NULL UNIQUE CHECK (length(listing_id) > 0),
  nft_id uuid NOT NULL,
  seller_wallet_address text NOT NULL CHECK (length(seller_wallet_address) > 0),
  price numeric,
  price_asset text NOT NULL DEFAULT 'USDC'::text,
  status USER-DEFINED NOT NULL DEFAULT 'active'::listing_status,
  title text NOT NULL CHECK (length(title) > 0),
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  sold_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  buyer_wallet_address text,
  sale_price numeric,
  metadata jsonb DEFAULT '{}'::jsonb,
  profit_share_percentage numeric DEFAULT 0,
  CONSTRAINT marketplace_listings_pkey PRIMARY KEY (id),
  CONSTRAINT marketplace_listings_nft_id_fkey FOREIGN KEY (nft_id) REFERENCES public.vault_nfts(id)
);
CREATE TABLE public.nft_profit_stats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nft_id text NOT NULL UNIQUE,
  vault_id uuid NOT NULL,
  holder_wallet_address text NOT NULL,
  total_distributions_count integer DEFAULT 0,
  total_profit_received numeric DEFAULT 0,
  last_distribution_amount numeric,
  last_distribution_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT nft_profit_stats_pkey PRIMARY KEY (id),
  CONSTRAINT nft_profit_stats_vault_id_fkey FOREIGN KEY (vault_id) REFERENCES public.vaults(id)
);
CREATE TABLE public.profit_distributions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vault_id uuid NOT NULL,
  distribution_type text NOT NULL CHECK (distribution_type = ANY (ARRAY['nft_holder'::text, 'vault_subscriber'::text])),
  transaction_hash text,
  contract_address text NOT NULL,
  recipient_wallet_address text NOT NULL,
  recipient_nft_id text,
  recipient_subscription_id uuid,
  token_address text NOT NULL,
  token_symbol text,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  profit_share_percentage numeric CHECK (profit_share_percentage IS NULL OR profit_share_percentage > 0::numeric AND profit_share_percentage <= 100::numeric),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  error_message text,
  initiated_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT profit_distributions_pkey PRIMARY KEY (id),
  CONSTRAINT profit_distributions_vault_id_fkey FOREIGN KEY (vault_id) REFERENCES public.vaults(id)
);
CREATE TABLE public.quests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quest_key text NOT NULL UNIQUE CHECK (length(quest_key) > 0),
  title text NOT NULL,
  description text NOT NULL,
  category text NOT NULL,
  difficulty text NOT NULL,
  order_index integer NOT NULL,
  reward_nft_image text,
  reward_nft_name text NOT NULL,
  reward_nft_description text,
  validation_type text NOT NULL,
  validation_config jsonb DEFAULT '{}'::jsonb,
  hint_steps jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT quests_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscription_profit_stats (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subscription_id uuid NOT NULL UNIQUE,
  original_vault_id uuid NOT NULL,
  subscriber_wallet_address text NOT NULL,
  total_distributions_count integer DEFAULT 0,
  total_profit_shared numeric DEFAULT 0,
  last_distribution_amount numeric,
  last_distribution_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_profit_stats_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_profit_stats_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.vault_subscriptions(id),
  CONSTRAINT subscription_profit_stats_original_vault_id_fkey FOREIGN KEY (original_vault_id) REFERENCES public.vaults(id)
);
CREATE TABLE public.terminal_conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  session_id text NOT NULL UNIQUE,
  wallet_address text,
  title text NOT NULL,
  message_count integer DEFAULT 0,
  token_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT terminal_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT terminal_conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.terminal_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['user'::text, 'assistant'::text, 'system'::text, 'tool'::text])),
  content text NOT NULL,
  function_called text,
  function_result jsonb,
  message_type text DEFAULT 'text'::text,
  tool_call_id text,
  timestamp timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT terminal_messages_pkey PRIMARY KEY (id),
  CONSTRAINT terminal_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.terminal_conversations(id)
);
CREATE TABLE public.user_onboarding (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  has_seen_quest_modal boolean DEFAULT false,
  wants_quests boolean DEFAULT false,
  quests_started_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_onboarding_pkey PRIMARY KEY (id),
  CONSTRAINT user_onboarding_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_page_visits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  page_path text NOT NULL,
  visit_count integer DEFAULT 1,
  first_visited_at timestamp with time zone NOT NULL DEFAULT now(),
  last_visited_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_page_visits_pkey PRIMARY KEY (id),
  CONSTRAINT user_page_visits_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_quests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  quest_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'not_started'::text,
  progress jsonb DEFAULT '{}'::jsonb,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  claimed_at timestamp with time zone,
  nft_token_id text,
  nft_transaction_hash text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_quests_pkey PRIMARY KEY (id),
  CONSTRAINT user_quests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_quests_quest_id_fkey FOREIGN KEY (quest_id) REFERENCES public.quests(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  wallet_address text NOT NULL UNIQUE CHECK (length(wallet_address) > 0),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  profile jsonb DEFAULT '{}'::jsonb,
  network text DEFAULT 'futurenet'::text,
  last_login_at timestamp with time zone,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.vault_liquidity_positions (
  id integer NOT NULL DEFAULT nextval('vault_liquidity_positions_id_seq'::regclass),
  vault_id character varying NOT NULL,
  contract_address character varying NOT NULL,
  pool_address character varying NOT NULL,
  token_a character varying NOT NULL,
  token_b character varying NOT NULL,
  lp_tokens bigint NOT NULL,
  amount_a_provided bigint NOT NULL,
  amount_b_provided bigint NOT NULL,
  timestamp bigint NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT vault_liquidity_positions_pkey PRIMARY KEY (id),
  CONSTRAINT fk_vault_liquidity FOREIGN KEY (vault_id) REFERENCES public.vaults(vault_id)
);
CREATE TABLE public.vault_nfts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nft_id text NOT NULL UNIQUE CHECK (length(nft_id) > 0),
  vault_id uuid NOT NULL,
  token_id text NOT NULL UNIQUE CHECK (length(token_id) > 0),
  contract_address text NOT NULL,
  original_owner text NOT NULL,
  current_holder text NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  minted_at timestamp with time zone NOT NULL DEFAULT now(),
  last_transfer_at timestamp with time zone,
  total_profits_earned numeric DEFAULT 0,
  last_profit_distribution timestamp with time zone,
  last_profit_distribution_id uuid,
  CONSTRAINT vault_nfts_pkey PRIMARY KEY (id),
  CONSTRAINT vault_nfts_vault_id_fkey FOREIGN KEY (vault_id) REFERENCES public.vaults(id),
  CONSTRAINT vault_nfts_last_profit_distribution_id_fkey FOREIGN KEY (last_profit_distribution_id) REFERENCES public.profit_distributions(id)
);
CREATE TABLE public.vault_performance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vault_id uuid NOT NULL,
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  total_value numeric NOT NULL CHECK (total_value >= 0::numeric),
  share_price numeric NOT NULL CHECK (share_price > 0::numeric),
  returns_24h numeric,
  returns_7d numeric,
  returns_30d numeric,
  returns_all_time numeric,
  apy_current numeric,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT vault_performance_pkey PRIMARY KEY (id),
  CONSTRAINT vault_performance_vault_id_fkey FOREIGN KEY (vault_id) REFERENCES public.vaults(id)
);
CREATE TABLE public.vault_staking_positions (
  id integer NOT NULL DEFAULT nextval('vault_staking_positions_id_seq'::regclass),
  vault_id character varying NOT NULL,
  contract_address character varying NOT NULL,
  staking_pool character varying NOT NULL,
  original_token character varying NOT NULL,
  staked_amount bigint NOT NULL,
  st_token_amount bigint NOT NULL,
  timestamp bigint NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT vault_staking_positions_pkey PRIMARY KEY (id),
  CONSTRAINT fk_vault_staking FOREIGN KEY (vault_id) REFERENCES public.vaults(vault_id)
);
CREATE TABLE public.vault_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  original_vault_id uuid NOT NULL,
  subscribed_vault_id uuid NOT NULL,
  subscriber_wallet_address text NOT NULL,
  profit_share_percentage numeric NOT NULL CHECK (profit_share_percentage > 0::numeric AND profit_share_percentage <= 100::numeric),
  total_profits_shared numeric DEFAULT 0,
  last_profit_share_at timestamp with time zone,
  subscribed_at timestamp with time zone NOT NULL DEFAULT now(),
  last_profit_distribution_id uuid,
  CONSTRAINT vault_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT vault_subscriptions_original_vault_id_fkey FOREIGN KEY (original_vault_id) REFERENCES public.vaults(id),
  CONSTRAINT vault_subscriptions_subscribed_vault_id_fkey FOREIGN KEY (subscribed_vault_id) REFERENCES public.vaults(id),
  CONSTRAINT vault_subscriptions_subscriber_wallet_address_fkey FOREIGN KEY (subscriber_wallet_address) REFERENCES public.users(wallet_address),
  CONSTRAINT vault_subscriptions_last_profit_distribution_id_fkey FOREIGN KEY (last_profit_distribution_id) REFERENCES public.profit_distributions(id)
);
CREATE TABLE public.vault_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vault_id uuid NOT NULL,
  user_address text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['deposit'::text, 'withdrawal'::text])),
  amount_xlm numeric NOT NULL CHECK (amount_xlm > 0::numeric),
  amount_usd numeric NOT NULL CHECK (amount_usd > 0::numeric),
  shares numeric NOT NULL CHECK (shares > 0::numeric),
  xlm_price numeric NOT NULL CHECK (xlm_price > 0::numeric),
  share_price numeric NOT NULL CHECK (share_price > 0::numeric),
  transaction_hash text,
  block_number bigint,
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT vault_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT vault_transactions_vault_id_fkey FOREIGN KEY (vault_id) REFERENCES public.vaults(id)
);
CREATE TABLE public.vaults (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vault_id text NOT NULL UNIQUE CHECK (length(vault_id) > 0),
  owner_wallet_address text NOT NULL,
  contract_address text UNIQUE,
  name text NOT NULL,
  description text,
  config jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(config) = 'object'::text),
  status USER-DEFINED NOT NULL DEFAULT 'draft'::vault_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deployed_at timestamp with time zone,
  total_value_locked numeric DEFAULT 0,
  network text NOT NULL DEFAULT 'testnet'::text,
  CONSTRAINT vaults_pkey PRIMARY KEY (id),
  CONSTRAINT vaults_owner_wallet_address_fkey FOREIGN KEY (owner_wallet_address) REFERENCES public.users(wallet_address)
);